CI_CD:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "ryedgjb-qf09437"
      user: "kirillkonkov2023"
      password: "Kirill2004@"
      role: "dbt_role"
      database: "dbt_db"
      warehouse: "dbt_wh"
      schema: "dbt_schema"
      threads: 4
      client_session_keep_alive: false