name: Workflow to Setup Snowflake Environment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/setup_snowflake_env.yml'
  workflow_dispatch: # To allow for manual trigger

jobs:
  setup_snowflake:
    runs-on: windows-latest

    env: # only these are needed for this first workflow
      SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/windows_x86_64/snowsql-1.2.29-windows_x86_64.msi
          msiexec /i snowsql-1.2.29-windows_x86_64.msi /quiet /norestart

      - name: Locate SnowSQL
        id: locate-snowsql
        run: |
          $snowsqlPath = "C:\Program Files\Snowflake SnowSQL\bin\snowsql.exe"
          if (Test-Path $snowsqlPath) {
            echo "##[set-output name=snowsql_path;]$snowsqlPath"
          } else {
            Write-Error "SnowSQL not found"
          }

      - name: Execute Snowflake Setup Script
        run: |
          $snowsqlPath = "${{ steps.locate-snowsql.outputs.snowsql_path }}"
          & $snowsqlPath -a $env:SNOWSQL_ACCOUNT -u $env:SNOWSQL_USER -p $env:SNOWSQL_PWD -f scripts/setup_snowflake_env.sql -o friendly=false