name: Workflow to Setup Snowflake Environment

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/setup_snowflake_env.yml'
  workflow_dispatch: # To allow for manual trigger

jobs:
  setup_snowflake:
    runs-on: windows-latest

    env:
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/windows_x86_64/snowsql-1.2.29-windows_x86_64.msi
          msiexec /i snowsql-1.2.29-windows_x86_64.msi /quiet /norestart

      - name: Locate SnowSQL
        id: locate-snowsql
        run: |
          $snowsqlPath = "C:\Program Files\Snowflake SnowSQL\bin\snowsql.exe"
          if (Test-Path $snowsqlPath) {
            echo "##[set-output name=snowsql_path;]$snowsqlPath"
          } else {
            Write-Error "SnowSQL not found"
          }

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Debug Secrets
        run: |
          echo "SNOWFLAKE_ACCOUNT: $env:SNOWFLAKE_ACCOUNT"
          echo "SNOWFLAKE_USERNAME: $env:SNOWFLAKE_USERNAME"
        shell: powershell

      - name: Create .dbt directory and add profiles.yml
        run: |
          mkdir -p C:\Users\runneradmin\.dbt
          echo "CI_CD:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: '{{ env_var("SNOWFLAKE_ACCOUNT") }}'
                user: '{{ env_var("SNOWFLAKE_USERNAME") }}'
                password: '{{ env_var("SNOWFLAKE_PASSWORD") }}'
                role: 'YOUR_ROLE_HERE'
                database: 'YOUR_DATABASE_HERE'
                warehouse: 'YOUR_WAREHOUSE_HERE'
                schema: 'YOUR_SCHEMA_HERE'
                threads: 4
                client_session_keep_alive: false" > C:\Users\runneradmin\.dbt\profiles.yml

      - name: Run dbt debug
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USERNAME }}
        run: dbt debug

      - name: Execute Snowflake Setup Script
        run: |
          $snowsqlPath = "${{ steps.locate-snowsql.outputs.snowsql_path }}"
          & $snowsqlPath -a $env:SNOWFLAKE_ACCOUNT -u $env:SNOWFLAKE_USERNAME -p $env:SNOWFLAKE_PASSWORD -f scripts/setup_snowflake_env.sql -o friendly=false
        shell: powershell
